### ISSUE TITLE
TCP Client: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access mem

### ISSUE THREAD

**Issue by eviltik** [song940/node-dns#32]
Hi !

Times to times, using TCP client, i have this error :
```
eviltik@debian:/code/eviltik/node-dns$ node --trace-warnings example/client/tcp.js
(node:5179) UnhandledPromiseRejectionWarning: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:81:11)
    at Buffer.readUInt8 (internal/buffer.js:249:5)
    at Function.BufferReader.read (/code/eviltik/node-dns/lib/reader.js:39:23)
    at BufferReader.read (/code/eviltik/node-dns/lib/reader.js:49:26)
    at Function.Packet.Header.parse (/code/eviltik/node-dns/packet.js:200:27)
    at Function.Packet.parse (/code/eviltik/node-dns/packet.js:116:33)
    at /code/eviltik/node-dns/client/tcp.js:18:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /code/eviltik/node-dns/example/client/tcp.js:6:20
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:5179) RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:81:11)
    at Buffer.readUInt8 (internal/buffer.js:249:5)
    at Function.BufferReader.read (/code/eviltik/node-dns/lib/reader.js:39:23)
    at BufferReader.read (/code/eviltik/node-dns/lib/reader.js:49:26)
    at Function.Packet.Header.parse (/code/eviltik/node-dns/packet.js:200:27)
    at Function.Packet.parse (/code/eviltik/node-dns/packet.js:116:33)
    at /code/eviltik/node-dns/client/tcp.js:18:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /code/eviltik/node-dns/example/client/tcp.js:6:20
(node:5179) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

I had a chance to sniff it using tcpdump. In the zip file, you will find a successfull result (OK) and an errored result (KO)

It's too low level for me, i can't help/understand here. We can see that in the KO trace, 2 packets are missing at the end: FIN,ACK from the server, followed by an ACK from the client. Note that on my side (inside a Virtualbox VM) it append randomly, let's say one error each 10 resolve). Hard to reproduce.

![image](https://user-images.githubusercontent.com/4477890/110322793-f0588880-8013-11eb-8cb3-f93bc9c25664.png)

[dns2_TCP_OK_and_KO.zip](https://github.com/song940/node-dns/files/6101360/dns2_TCP_OK_and_KO.zip)

**Comment by eviltik** [comment]
This append (randomly) only using TCP with cloudflare dns server (1.1.1.1 and 1.0.0.1)
