### ISSUE TITLE
Server stopping instantly?

### ISSUE THREAD

**Issue by BasToTheMax** [song940/node-dns#73]
my code:
```
const dns2 = require('dns2');
const chalk = require('chalk');

const { Packet } = dns2;

var port = process.env['SERVER_PORT'];
if (!port) {
  console.log(chalk.yellow(`\t'SERVER_PORT' env variable not found, using port of config: ${53}`))
  port = 53;
}

const server = dns2.createServer({
  udp: true,
  tcp: true,
  handle: (request, send, rinfo) => {
    const response = Packet.createResponseFromRequest(request);
    const [ question ] = request.questions;
    const { name } = question;
    response.answers.push({
      name,
      type: Packet.TYPE.A,
      class: Packet.CLASS.IN,
      ttl: 300,
      address: '8.8.8.8'
    });
    send(response);
  }
});

server.on('request', (request, response, rinfo) => {
  console.log(request.header.id, request.questions[0]);
});

server.on('requestError', (error) => {
  console.log('Client sent an invalid request', error);
});

server.on('listening', () => {
  console.log(server.addresses());
});

server.on('close', () => {
  console.log('server closed');
});

server.listen({
  // Optionally specify port, address and/or the family of socket() for udp server:
  udp: { 
    port: port,
    address: "0.0.0.0",
    type: "udp4",  // IPv4 or IPv6 (Must be either "udp4" or "udp6")
  },
  
  // Optionally specify port and/or address for tcp server:
  tcp: { 
    port: port,
    address: "0.0.0.0",
  },
});

// eventually
server.close();
```

logs:
```
Action reload started
Action reload completed
	'SERVER_PORT' env variable not found, using port of config: 53
server closed
Client sent an invalid request RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at Buffer.readUInt8 (internal/buffer.js:137:5)
    at Function.BufferReader.read (/var/lib/pterodactyl/volumes/d09a0f8c-ede3-4ae8-9dd0-6f423af44b74/node_modules/dns2/lib/reader.js:38:24)
    at BufferReader.read (/var/lib/pterodactyl/volumes/d09a0f8c-ede3-4ae8-9dd0-6f423af44b74/node_modules/dns2/lib/reader.js:48:28)
    at Function.Packet.Header.parse (/var/lib/pterodactyl/volumes/d09a0f8c-ede3-4ae8-9dd0-6f423af44b74/node_modules/dns2/packet.js:219:22)
    at Function.Packet.parse (/var/lib/pterodactyl/volumes/d09a0f8c-ede3-4ae8-9dd0-6f423af44b74/node_modules/dns2/packet.js:121:33)
    at Server.handle (/var/lib/pterodactyl/volumes/d09a0f8c-ede3-4ae8-9dd0-6f423af44b74/node_modules/dns2/server/tcp.js:16:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by BasToTheMax** [comment]
nvm
